resources:
- name: ci
  type: git
  check_every: 10m
  source:
    uri: ((ci-repo))
    branch: ((ci-branch))
    paths:
    - dockerfiles
- name: docker.base-ci
  type: docker-image
  source:
    repository: ((docker-organization))/base-ci
    username: ((dockerhub.username))
    password: ((dockerhub.password))

jobs:
- name: base-ci
  plan:
  - aggregate:
    - get: ci
      trigger: true
  - put: docker.base-ci
    params:
      build: ci/dockerfiles/base-ci
      build_args:
        GOPROXY: ((goproxy))
