---
platform: linux
image_resource:
 type: docker-image
 source:
   repository: cfcontainerization/go-tools
   tag: latest
inputs:
- name: src
  path: src/code.cloudfoundry.org/quarks-operator
- name: ci
- name: s3.build-number
  optional: true
outputs:
- name: code-coverage
run:
  path: ci/succeed_unless
  args:
    - src/code.cloudfoundry.org/quarks-operator
    - ci/pipelines/tasks/test.sh
