resources:
- name: src
  type: git
  source:
    uri: ((src-repo))
    branch: master
- name: ci
  type: git
  source:
    uri: ((ci-repo))
    branch: ((ci-branch))
- name: docker.cf-operator-rc
  type: docker-image
  source:
    repository: ((docker-organization))/((docker-candidate-repo))
    username: ((dockerhub.username))
    password: ((dockerhub.password))
- name: 12h
  type: time
  check_every: 10m
  source:
    interval: 12h

jobs:
- name: clean-k8s
  serial: true
  plan:
  - in_parallel:
    - get: ci
    - get: 12h
      trigger: true
  - task: clean-dino-k8s
    params:
      ibmcloud_apikey: ((ibmcloud.key-value))
      ibmcloud_server: ((ibmcloud.server))
      ibmcloud_region: ((ibmcloud.region))
      ibmcloud_cluster: ((ibmcloud-cluster))
    file: ci/pipelines/cf-operator-nightly/tasks/clean-k8s.yml
  - task: clean-k8s
    params:
      ibmcloud_apikey: ((ibmcloud.key-value))
      ibmcloud_server: ((ibmcloud.server))
      ibmcloud_region: ((ibmcloud.region))
      ibmcloud_cluster: ((ibmcloud-cluster2))
    file: ci/pipelines/cf-operator-nightly/tasks/clean-k8s.yml

- name: build
  serial: true
  plan:
  - in_parallel:
    - get: ci
    - get: src
    - get: 12h
      trigger: true
      passed: [clean-k8s]
  - task: build
    file: ci/pipelines/tasks/build.yml
    params:
      GOPROXY: ((goproxy))
  - put: docker.cf-operator-rc
    params:
      build: src
      build_args:
        GOPROXY: ((goproxy))
      tag: docker/tag

- name: build-helm
  plan:
  - in_parallel:
    - get: ci
    - get: src
    - get: 12h
      trigger: true
      passed: [clean-k8s]
  - task: build
    file: ci/pipelines/tasks/build-helm.yml

- name: test
  serial: true
  plan:
  - in_parallel:
    - get: ci
    - get: src
      passed: [build]
      trigger: true
    - get: 12h
      trigger: true
  - task: lint
    file: ci/pipelines/tasks/lint.yml
    params:
      GOPROXY: ((goproxy))
  - task: test-unit
    file: ci/pipelines/tasks/test.yml
    params:
      GOPROXY: ((goproxy))
  - in_parallel:
    - task: test-integration
      params:
        ibmcloud_apikey: ((ibmcloud.key-value))
        ibmcloud_server: ((ibmcloud.server))
        ibmcloud_region: ((ibmcloud.region))
        ibmcloud_cluster: ((ibmcloud-cluster))
        ssh_server_ip: ((ssh-server.ip))
        ssh_server_user: ((ssh-server.user))
        ssh_server_key: ((ssh-server.key))
        OPERATOR_TEST_STORAGE_CLASS: ((storageclass))
        DOCKER_IMAGE_REPOSITORY: ((docker-candidate-repo))
        GOPROXY: ((goproxy))
      file: ci/pipelines/tasks/test-integration.yml
    - task: test-helm-e2e
      params:
        ibmcloud_apikey: ((ibmcloud.key-value))
        ibmcloud_server: ((ibmcloud.server))
        ibmcloud_region: ((ibmcloud.region))
        ibmcloud_cluster: ((ibmcloud-cluster))
        ssh_server_ip: ((ssh-server.ip))
        ssh_server_user: ((ssh-server.user))
        ssh_server_key: ((ssh-server.key))
        OPERATOR_TEST_STORAGE_CLASS: ((storageclass))
        DOCKER_IMAGE_REPOSITORY: ((docker-candidate-repo))
      file: ci/pipelines/tasks/test-helm-e2e.yml

