---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: havener/build-environment
    tag: latest
inputs:
- name: s3.stemcell-version
- name: ci
- name: release
- name: s3.fissile-linux
params:
  STEMCELL_REPOSITORY:
  RELEASE_NAME:
  DOCKER_TEAM_USERNAME:
  DOCKER_TEAM_PASSWORD_RW:
  REGISTRY_NAMESPACE:
run:
  path: ci/pipelines/cf-operator-testing-image/tasks/build.sh
