---
platform: linux
image_resource:
 type: docker-image
 source:
   repository: cfcontainerization/go-tools
   tag: latest
inputs:
- name: src
  path: src/code.cloudfoundry.org/quarks-operator
- name: ci
- name: s3.build-number
  optional: true
- name: s3.code-coverage-unit
- name: s3.code-coverage-integration
run:
  path: ci/pipelines/cf-operator/tasks/coverage.sh
