---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: cfcontainerization/go-tools
    tag: latest
inputs:
- name: ci
- name: docker.coredns
- name: src
run:
  path: ci/pipelines/cf-operator/tasks/create-coredns-pr.sh
